UwUMaker-c-sources-y += main.c

UwUMaker-c-flags-y += -I$(ROOT_PROJECT_DIR)\
	-I$(ROOT_PROJECT_DIR)/test/

UwUMaker-is-executable := y
UwUMaker-name := FlupTest

UwUMaker-shared-lib-subprojects-y += $(ROOT_PROJECT_DIR)

