
UwUMaker-c-sources-y += linked_list.c \
	linked_list_impl_ilist.c \
	dyn_array.c dyn_array_impl_ilist.c \
	buffer.c string_map.c

UwUMaker-dirs-y += buffer tree

UwUMaker-c-flags-y += -UFLUP_LOG_CATEGORY -DFLUP_LOG_CATEGORY='"Data Structures"'
